title: Matheus Amazonas
description: Game developer
baseurl: /
url: https://matheusamazonas.net
theme: jekyll-theme-cayman
homepage: /index.html

# Author
author:
  name: Matheus Amazonas
  email: matheus.amazonas@gmail.com


# Social Networks
social-links:
- id: email
  link: 'mailto:matheus.amazonas@gmail.com'
- id: github
  link: https://github.com/matheusamazonas
- id: wordpress
  link: http://blog.matheusamazonas.net
- id: linkedin
  link: https://www.linkedin.com/in/matheusamazonas/
- id: facebook
  link: https://www.facebook.com/matheus.amazonas.9
- id: youtube
  link: https://www.youtube.com/user/matheuzamazonas/videos

navigation:
- text: Home
  url: /
  external: false
- text: About
  url: /about.html
  external: false
- text: Portfolio
  url: /portfolio.html
  external: false
- text: Blog
  url: http://blog.matheusamazonas.net
  external: true

portfolio: /portfolio.html