title: Matheus Amazonas
tagline: Matheus Amazonas
suffix: Game Developer
description: Video game developer with 5 years of experience on Dutch, American and Brazilian markets.
baseurl: /
url: matheusamazonas.net
theme: jekyll-theme-cayman
homepage: /index.html
sass:
  style: compressed

# Author
author:
  name: Matheus Amazonas
  email: matheus.amazonas@gmail.com

plugins:
  - jekyll-target-blank

# Include
include:
  - _redirects

# Social Networks
social-links:
- id: email
  link: 'mailto:matheus.amazonas@gmail.com'
  alt: 'Email Matheus'
- id: github
  link: https://github.com/matheusamazonas
  alt: "Matheus' GitHub"
- id: wordpress
  link: https://blog.lslabs.dev
  alt: "Matheus' blog"
- id: linkedin
  link: https://www.linkedin.com/in/matheusamazonas/
  alt: "Matheus' LinkedIn"
- id: facebook
  link: https://www.facebook.com/matheus.amazonas.9
  alt: "Matheus' Facebook"
- id: youtube
  link: https://www.youtube.com/user/matheuzamazonas/videos
  alt: "Matheus' YouTube"

navigation:
- text: Home
  url: /
  external: false
- text: About
  url: /about.html
  external: false
- text: Portfolio
  url: /portfolio.html
  external: false
- text: Blog
  url: https://blog.lslabs.dev
  external: true
- text: Contact
  url: /contact.html
  external: false

portfolio: /portfolio.html